/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
    './styles/**/*.css',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary':                  '#750003',
        'primary-container':        '#9e090b',
        'on-primary':               '#ffffff',
        'on-primary-container':     '#ffa89d',
        'primary-fixed':            '#ffdad5',
        'primary-fixed-dim':        '#ffb4aa',
        'on-primary-fixed':         '#410001',
        'on-primary-fixed-variant': '#930006',
        'secondary':                '#2c5fa0',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#8ab8ff',
        'on-secondary-container':   '#054787',
        'secondary-fixed':          '#d5e3ff',
        'secondary-fixed-dim':      '#a7c8ff',
        'on-secondary-fixed':       '#001b3b',
        'on-secondary-fixed-variant':'#044787',
        'tertiary':                 '#735c00',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#cca730',
        'on-tertiary-container':    '#4f3e00',
        'tertiary-fixed':           '#ffe088',
        'tertiary-fixed-dim':       '#e9c349',
        'on-tertiary-fixed':        '#241a00',
        'on-tertiary-fixed-variant':'#574500',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'background':               '#fcf9f8',
        'on-background':            '#1c1b1b',
        'surface':                  '#fcf9f8',
        'on-surface':               '#1c1b1b',
        'surface-variant':          '#e5e2e1',
        'on-surface-variant':       '#5b403d',
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f6f3f2',
        'surface-container':        '#f0eded',
        'surface-container-high':   '#eae7e7',
        'surface-container-highest':'#e5e2e1',
        'surface-dim':              '#dcd9d9',
        'surface-bright':           '#fcf9f8',
        'surface-tint':             '#b7211b',
        'inverse-surface':          '#313030',
        'inverse-on-surface':       '#f3f0ef',
        'inverse-primary':          '#ffb4aa',
        'outline':                  '#8f706b',
        'outline-variant':          '#e3beb9',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body:     ['"Plus Jakarta Sans"', 'sans-serif'],
        label:    ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
